services:
  - type: web
    name: crypto-zenith
    runtime: static
    rootDir: frontend 3
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_CHAIN_ID
        value: 0x38
      - key: VITE_NBT_TOKEN
        value: 0xD0F2A86C7EbCeE887F5bFB86771f994CD142bD04
      - key: VITE_STAKING_BANK
        value: 0x903fcce5d67648FBE6Dccc9806e3bd7D303380fD
      - key: VITE_NBT_PAIR
        value: ""
      - key: VITE_FEE_TOKEN
        value: 
