services:
  - type: web
    name: crypto-zenith
    runtime: static
    rootDir: frontend 3
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_CHAIN_ID
        value: 0x61
      - key: VITE_NBT_TOKEN
        value: 0x99fbDdb26bc6b10DC9df80d6c6D943812047f406
      - key: VITE_STAKING_BANK
        value: 0xB110ea48824383BAbeDE6ba7E19d5E01089De6cc
      - key: VITE_NBT_PAIR
        value: ""
      - key: VITE_FEE_TOKEN
        value: 0x99fbDdb26bc6b10DC9df80d6c6D943812047f406
