export const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const NBT_TOKEN_ABI = [
  ...ERC20_ABI,
  "function getFeeConfig() view returns (uint256 _buyFee, uint256 _sellFee, address _feeReceiver)",
  "function isExcludedFromFee(address) view returns (bool)",
  "function burn(uint256 amount)",
];

export const STAKING_BANK_ABI = [
  "function saleToken() view returns (address)",
  "function paymentToken() view returns (address)",
  "function tokenPrice() view returns (uint256)",
  "function totalSold() view returns (uint256)",
  "function totalUSDTReceived() view returns (uint256)",
  "function totalRewardsDistributed() view returns (uint256)",
  "function totalInterestClaimed() view returns (uint256)",
  "function dailyInterestRateBps() view returns (uint256)",
  "function teamWallet() view returns (address)",
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function paused() view returns (bool)",
  "function referrerOf(address user) view returns (address)",
  "function directRewards(address user) view returns (uint256)",
  "function indirectRewards(address user) view returns (uint256)",
  "function teamRewards(address user) view returns (uint256)",
  "function totalPurchased(address user) view returns (uint256)",
  "function totalClaimed(address user) view returns (uint256)",
  "function lastInterestClaimTime(address user) view returns (uint256)",
  "function pendingInterest(address user) view returns (uint256)",
  "function getUserInfo(address user) view returns (address referrer, uint256 purchased, uint256 directReward, uint256 indirectReward, uint256 teamReward, uint256 claimed, uint256 referralCount)",
  "function getReferralsPaginated(address user, uint256 offset, uint256 limit) view returns (address[] result, uint256 total)",
  "function getSaleStatus() view returns (uint256 _totalSold, uint256 _totalUSDTReceived, uint256 _totalRewardsDistributed, uint256 _tokenPrice, bool _paused)",
  "function pendingRewards(address user) view returns (uint256)",
  "function referrals(address user) view returns (address[])",
  "function buy(uint256 usdtAmount, address referrer)",
  "function claimRewards()",
  "function setReferrer(address referrer)",
  "function claimInterest()",
  "function setDailyInterestRateBps(uint256 bps)",
  "function fundInterestPool(uint256 amount)",
  "function setTokenPrice(uint256 price)",
  "function setTeamWallet(address wallet)",
  "function withdrawUSDT(uint256 amount)",
  "function pause()",
  "function unpause()",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "event Purchased(address indexed buyer, address indexed referrer, uint256 usdtAmount, uint256 tokenAmount)",
  "event ReferrerSet(address indexed user, address indexed referrer)",
  "event RewardsClaimed(address indexed user, uint256 directAmount, uint256 indirectAmount, uint256 teamAmount)",
  "event TokenPriceUpdated(uint256 price)",
  "event TeamWalletUpdated(address wallet)",
  "event Paused()",
  "event Unpaused()",
  "event USDTWithdrawn(address indexed to, uint256 amount)",
  "event InterestClaimed(address indexed user, uint256 amount)",
  "event InterestRateUpdated(uint256 bps)",
  "event InterestPoolFunded(address indexed funder, uint256 amount)",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
];
