export const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const NBT_TOKEN_ABI = [
  ...ERC20_ABI,
  "function getFeeConfig() view returns (uint256 _buyFee, uint256 _sellFee, address _feeReceiver)",
  "function isExcludedFromFee(address) view returns (bool)",
  "function burn(uint256 amount)",
];

export const STAKING_BANK_ABI = [
  "function stakingToken() view returns (address)",
  "function rewardToken() view returns (address)",
  "function interactionFeeToken() view returns (address)",
  "function totalStaked() view returns (uint256)",
  "function totalRankDistributed() view returns (uint256)",
  "function totalRankClaimed() view returns (uint256)",
  "function totalInviteRewardsAccrued() view returns (uint256)",
  "function totalInviteRewardsClaimed() view returns (uint256)",
  "function interactionFee() view returns (uint256)",
  "function inviteReward() view returns (uint256)",
  "function stakeValueRate() view returns (uint256)",
  "function startTime() view returns (uint256)",
  "function currentEpochId() view returns (uint256)",
  "function owner() view returns (address)",
  "function operators(address) view returns (bool)",
  "function paused() view returns (bool)",
  "function userInfo(address) view returns (uint256 totalStaked, uint256 totalWithdrawn, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralStakeVolume, uint256 pendingInviteRewards, uint256 totalInviteClaimed, uint256 pendingRankRewards, uint256 totalRankClaimed)",
  "function stakeRecords(address user, uint256 stakeId) view returns (uint256 amount, uint256 scoreValue, uint256 startTime, bool active)",
  "function getUserInfo(address user) view returns (tuple(uint256 totalStaked, uint256 totalWithdrawn, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralStakeVolume, uint256 pendingInviteRewards, uint256 totalInviteClaimed, uint256 pendingRankRewards, uint256 totalRankClaimed) info, uint256 pendingRewards, uint256 totalClaimed, uint256 rank)",
  "function getUserStakes(address user) view returns (uint256[] stakeIds, uint256[] amounts, uint256[] scoreValues, uint256[] startTimes, bool[] actives)",
  "function getStakeRecord(address user, uint256 stakeId) view returns (uint256 amount, uint256 scoreValue, uint256 startTime, bool active)",
  "function pendingRewardAll(address user) view returns (uint256)",
  "function getMiningStatus() view returns (uint256 _totalStaked, uint256 _totalDistributed, uint256 _claimableRewards, bool _releaseInProgress, uint256 _startTime, uint256 _rankedNodeCount)",
  "function getInteractionFeeConfig() view returns (address feeToken, uint256 fee, address receiverA, address receiverB)",
  "function getCurrentRelease() view returns (uint256 epochId, uint256 amount, uint256 totalNodes, uint256 nextRank, uint256 allocatedAmount, bool finalized)",
  "function getNodeRank(address node) view returns (uint256)",
  "function getRankedNodeCount() view returns (uint256)",
  "function getRankedNodes(uint256 offset, uint256 limit) view returns (address[] nodes, uint256[] scores, uint256 total)",
  "function getRankRewardPreview(uint256 amount, uint256 totalNodes, uint256 rank) view returns (uint256)",
  "function getReferrals(address user) view returns (address[])",
  "function getReferralsPaginated(address user, uint256 offset, uint256 limit) view returns (address[] result, uint256 total)",
  "function hasReferrer(address user) view returns (bool)",
  "function stake(uint256 amount, address referrer) payable",
  "function withdraw(uint256 stakeId) payable",
  "function setReferrer(address referrer) payable",
  "function claimNodeRewards() payable",
  "function claimReferralRewards() payable",
  "function claimAll() payable",
  "function compoundNodeRewards(address referrer) payable",
  "function openMonthlyRelease(uint256 amount)",
  "function allocateMonthlyRelease(uint256 maxCount)",
  "function setInteractionFeeConfig(address feeToken, uint256 fee, address receiverA, address receiverB)",
  "function setInviteReward(uint256 reward)",
  "function setStakeValueRate(uint256 rate)",
  "function setOperator(address operator, bool status)",
  "function pause()",
  "function unpause()",
  "function recoverWrongToken(address token, address to, uint256 amount)",
  "event Deposit(address indexed user, address indexed referrer, uint256 indexed stakeId, uint256 amount)",
  "event Withdraw(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event ReferrerSet(address indexed user, address indexed referrer)",
  "event ReferralQualified(address indexed referrer, address indexed user, uint256 inviteReward)",
  "event NodeScoreUpdated(address indexed node, uint256 score, uint256 rank)",
  "event NodeRewardsClaimed(address indexed user, uint256 inviteReward, uint256 rankReward)",
  "event NodeRewardsCompounded(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event MonthlyReleaseOpened(uint256 indexed epochId, uint256 amount, uint256 totalNodes)",
  "event RankRewardAllocated(uint256 indexed epochId, address indexed node, uint256 rank, uint256 amount)",
  "event MonthlyReleaseFinalized(uint256 indexed epochId, uint256 amount)",
  "event InteractionFeePaid(address indexed user, address indexed token, uint256 totalFee, address receiverA, address receiverB)",
];
