export const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const NBT_TOKEN_ABI = [
  ...ERC20_ABI,
  "function buyFee() view returns (uint256)",
  "function sellFee() view returns (uint256)",
  "function feeReceiver() view returns (address)",
  "function FEE_BASE() view returns (uint256)",
  "function isPair(address) view returns (bool)",
  "function isExcludedFromFee(address) view returns (bool)",
  "function getFeeConfig() view returns (uint256 _buyFee, uint256 _sellFee, address _feeReceiver)",
  "function calculateSellAmount(uint256 amount) view returns (uint256 feeAmount, uint256 receiveAmount)",
  "function calculateBuyAmount(uint256 amount) view returns (uint256 feeAmount, uint256 receiveAmount)",
  "function burn(uint256 amount)",
];

export const STAKING_BANK_ABI = [
  "function stakingToken() view returns (address)",
  "function rewardToken() view returns (address)",
  "function totalStaked() view returns (uint256)",
  "function totalRewards() view returns (uint256)",
  "function totalMiningDistributed() view returns (uint256)",
  "function totalReferralAccrued() view returns (uint256)",
  "function totalReferralClaimed() view returns (uint256)",
  "function startTime() view returns (uint256)",
  "function depositFee() view returns (uint256)",
  "function depositFeeReceiver() view returns (address)",
  "function miningEnded() view returns (bool)",
  "function RATE_BASE() view returns (uint256)",
  "function SECONDS_PER_DAY() view returns (uint256)",
  "function MAX_ACTIVE_STAKES() view returns (uint256)",
  "function owner() view returns (address)",
  "function operators(address) view returns (bool)",
  "function paused() view returns (bool)",
  "function userInfo(address) view returns (uint256 totalStaked, uint256 totalClaimed, uint256 stakeCount, uint256 activeStakeCount, address referrer, uint256 directReferrals, uint256 referralRewards, uint256 totalReferralClaimed)",
  "function stakeRecords(address, uint256) view returns (uint256 amount, uint256 lastUpdateTime, uint256 pendingRewards, uint256 unlockTime, uint8 tier, bool active)",
  "function pendingReward(address user, uint256 stakeId) view returns (uint256)",
  "function pendingRewardAll(address user) view returns (uint256)",
  "function getUserStakes(address user) view returns (uint256[] stakeIds, uint256[] amounts, uint256[] unlockTimes, uint8[] tiers, uint256[] pendingRewards, bool[] actives)",
  "function getStakeRecord(address user, uint256 stakeId) view returns (uint256 amount, uint256 unlockTime, uint8 tier, uint256 pending, bool active)",
  "function getUserInfo(address user) view returns (uint256 _totalStaked, uint256 _totalClaimed, uint256 _stakeCount, uint256 _pendingRewards, uint256 _activeStakeCount, address _referrer, uint256 _directReferrals, uint256 _referralRewards, uint256 _totalReferralClaimed)",
  "function getUserActiveStakeCount(address user) view returns (uint256 activeCount)",
  "function getMiningStatus() view returns (uint256 _totalStaked, uint256 _totalDistributed, uint256 _remainingRewards, bool _miningEnded, uint256 _startTime, uint256 _totalReferralDistributed)",
  "function pendingSyncRewards() view returns (uint256)",
  "function getDepositFeeConfig() view returns (uint256 _depositFee, address _depositFeeReceiver)",
  "function tierConfigs(uint8) view returns (uint256 duration, uint256 dailyRate)",
  "function getTierConfig(uint8 tier) view returns (uint256 duration, uint256 dailyRate, uint256 annualAPY)",
  "function getAllTierConfigs() view returns (uint256[4] durations, uint256[4] dailyRates, uint256[4] annualAPYs)",
  "function hasReferrer(address user) view returns (bool)",
  "function getReferralRates() view returns (uint256[])",
  "function getReferralLevels() view returns (uint256)",
  "function getReferrals(address user) view returns (address[])",
  "function getReferralsPaginated(address user, uint256 offset, uint256 limit) view returns (address[] result, uint256 total)",
  "function deposit(uint256 amount, uint8 tier)",
  "function withdraw(uint256 stakeId)",
  "function claim(uint256 stakeId)",
  "function claimAll()",
  "function setReferrer(address referrer)",
  "function claimReferralRewards()",
  "function fundRewards(uint256 amount)",
  "function syncRewards() returns (uint256 added)",
  "function setOperator(address operator, bool status)",
  "function setDepositFee(uint256 depositFee_, address receiver)",
  "function setTierConfig(uint8 tier, uint256 duration, uint256 dailyRate)",
  "function setReferralRates(uint256[] rates)",
  "function setMiningEnded(bool ended)",
  "function pause()",
  "function unpause()",
  "function recoverWrongToken(address token, uint256 amount)",
  "function adminWithdrawToken(address token, address to, uint256 amount)",
  "function adminWithdrawNative(address to, uint256 amount)",
  "event Deposit(address indexed user, uint256 indexed stakeId, uint256 amount, uint8 tier, uint256 unlockTime)",
  "event DepositFeeCollected(address indexed user, address indexed receiver, uint256 amount)",
  "event Withdraw(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event Claim(address indexed user, uint256 indexed stakeId, uint256 amount)",
  "event ClaimAll(address indexed user, uint256 amount)",
  "event ReferrerSet(address indexed user, address indexed referrer)",
  "event ReferralReward(address indexed user, address indexed referrer, uint256 level, uint256 amount)",
  "event ClaimReferralRewards(address indexed user, uint256 amount)",
  "event RewardsFunded(address indexed funder, uint256 amount)",
  "event RewardsSynced(address indexed caller, uint256 amount)",
  "event DepositFeeConfigUpdated(uint256 depositFee, address indexed receiver)",
  "event AdminTokenWithdrawn(address indexed token, address indexed to, uint256 amount)",
  "event AdminNativeWithdrawn(address indexed to, uint256 amount)",
  "event OperatorUpdated(address indexed operator, bool status)",
  "event TierConfigUpdated(uint8 tier, uint256 duration, uint256 dailyRate)",
  "event ReferralRatesUpdated(uint256[] rates)",
  "event MiningEnded(uint256 totalDistributed, uint256 totalReferralAccrued)",
];
