import { createContext, useContext, useState, useEffect } from "react";

// 翻译文件
const translations = {
  zh: {
    // Header
    header: {
      home: "首页",
      tokenMining: "节点排名",
      referral: "邀请节点",
      admin: "管理",
      switchNetwork: "切换网络",
      connecting: "连接中...",
      connectWallet: "连接钱包",
      whitepaper: "白皮书",
      telegram: "CZ人生频道",
      tagline: "链上巅峰 · CZ人生",
    },
    cz: {
      common: {
        person: "人",
        nodes: "个",
        copied: "已复制",
        copyLink: "复制推荐链接",
        copyExclusiveLink: "复制专属链接",
        refresh: "刷新",
        view: "查看",
        loadingMore: "加载中...",
        loadMore: "加载更多",
        rank: "排名",
        status: "状态",
        completed: "已完成",
        allocating: "分配中",
      },
      toast: {
        approveCz: "正在授权 CZ...",
        approveCzSuccess: "CZ 授权成功",
        approveFee: "正在授权操作...",
        approveFeeSuccess: "操作授权成功",
        invalidStakeAmount: "请输入有效质押数量",
        insufficientCz: "CZ 余额不足",
        staking: "质押 CZ 中...",
        stakeSuccess: "质押成功，节点排名已更新",
        withdrawing: "提取本金中...",
        withdrawSuccess: "本金已提取",
        claiming: "领取节点收益中...",
        claimSuccess: "节点收益已领取",
        compoundClaim: "正在领取收益...",
        compoundStake: "正在复投收益...",
        compoundSuccess: "复投成功，收益已转入质押",
        compoundUnavailable: "当前奖励币不能直接复投",
        noRewardsToCompound: "暂无可复投收益",
        linkCopied: "推荐链接已复制",
        copyFailed: "复制失败，请手动复制:",
        approveRelease: "正在授权月度释放 CZ...",
        approveSuccess: "授权成功",
        openRelease: "正在开启月度释放...",
        openReleaseSuccess: "月度释放已开启",
        allocateRelease: "正在分配排名奖励...",
        allocateReleaseSuccess: "本批排名奖励已入账",
        invalidAddress: "请填写有效地址",
        updateFee: "正在更新排名价值...",
        updateFeeSuccess: "排名价值已更新",
        updateInvite: "正在更新邀请奖励...",
        updateInviteSuccess: "邀请奖励已更新",
        pausing: "正在暂停...",
        resuming: "正在恢复...",
        paused: "合约已暂停",
        resumed: "合约已恢复",
      },
      home: {
        statStaked: "全网 CZ 质押",
        statDistributed: "已分配奖励",
        statNodes: "节点数量",
        bandTop10: "前 10 名",
        band11To50: "11-50 名",
        band51To100: "51-100 名",
        bandAfter100: "100 名以后",
        noteCore: "核心节点池",
        noteClimb: "攀登节点池",
        noteGrowth: "成长节点池",
        noteUniversal: "普惠节点池",
        badge: "100% 分配 · 无截留 · 链上排名",
        title2: "链上巅峰",
        intro1: "中本聪给了我们数字黄金，CZ人生给了我们链上分红。",
        intro2: "每个人，都是自己加密人生的主角。来，一起登顶加密之巅。",
        viewRank: "查看节点排名",
        inviteFriends: "邀请好友",
        goStake: "去质押",
        mechanismTitle: "CZ 人生节点机制",
        mechanism1: "你不需要质押，不需要申请节点。只要你的邀请人完成 CZ 质押，你就进入节点排名。",
        mechanism2: "每一个有效邀请质押，奖励 1 CZ。每月释放池再按排名分段 100% 分配给所有节点。",
        mechanism3: "排名越高，拿得越多。项目方不留一分，释放多少，分配多少。",
        monthlyTitle: "月度释放分配",
      },
      node: {
        bandTop10: "前 10 名",
        band11To50: "11-50 名",
        band51To100: "51-100 名",
        bandAfter100: "100 名以后",
        pageTitle: "CZ 人生节点排名",
        pageSubtitle: "邀请人质押，排名就是你的链上收益。",
        bandNote: "按月度释放池分配",
        releaseHint: "每月释放的 CZ 100% 全部分给节点，项目方不截留。释放分配期间会临时冻结排名变动，直到本月释放全部入账。",
        stakeTitle: "质押",
        referrerPlaceholder: "推荐人地址，可从推荐链接自动带入",
        stakeAmount: "质押数量",
        all: "全部",
        amountPlaceholder: "输入质押数量",
        stakeValue: "排名价值",
        inviteStakeReward: "邀请质押奖励",
        approveFee: "授权操作",
        approving: "授权中...",
        approveStake: "授权 CZ 质押",
        monthlyAllocating: "月度分配中",
        confirmStake: "确认质押",
        myRewards: "我的节点收益",
        statStaked: "全网质押 CZ",
        statDistributed: "已分配节点收益",
        statNodeCount: "节点总数",
        myRank: "我的排名",
        referralVolume: "邀请质押价值",
        directInvites: "有效邀请",
        invitePending: "邀请奖励待领",
        rankPending: "排名分红待领",
        approveFeeFirst: "先授权操作",
        claiming: "领取中...",
        claimAll: "领取全部节点收益",
        leaderboard: "节点排行榜",
        noRank: "暂无节点排名",
        myStakes: "我的质押",
        noStakes: "暂无质押记录",
        startTime: "开始时间",
        cannotWithdraw: "分配中不可提取",
        withdrawing: "提取中...",
        approveFeeBeforeWithdraw: "先授权操作",
        withdrawPrincipal: "提取本金",
        compoundRewards: "复投",
        compounding: "复投中...",
        approveCompound: "授权 CZ 复投",
        compoundUnavailable: "无法复投",
      },
      referral: {
        title: "邀请即节点",
        subtitle: "你不需要质押、不需要申请。只要邀请用户质押 CZ，你的节点排名就会更新。",
        myRank: "我的排名",
        directInvites: "有效邀请",
        referralVolume: "邀请质押价值",
        pendingRewards: "待领取收益",
        nodeRewards: "节点收益",
        invitePending: "邀请奖励待领",
        rankPending: "排名分红待领",
        totalClaimed: "累计已领",
        approveFee: "授权操作",
        claiming: "领取中...",
        claimRewards: "领取节点收益",
        myInvites: "我的邀请列表",
        totalPrefix: "共",
        noInvites: "暂无邀请成员",
      },
      admin: {
        title: "CZ 节点管理台",
        subtitle: "月度释放、排名分配、排名价值与邀请奖励配置",
        currentWallet: "当前钱包",
        totalStaked: "全网质押",
        nodeCount: "节点数",
        claimableRewards: "待领取奖励",
        monthlyRelease: "月度释放",
        releasePlaceholder: "释放 CZ 数量",
        batchPlaceholder: "每批分配节点数",
        rewardTopupAddress: "奖励充值地址",
        approveRelease: "授权释放 CZ",
        openRelease: "开启月度释放",
        totalRelease: "总释放",
        allocated: "已分配",
        allocateNext: "分配下一批",
        settings: "排名价值配置",
        stakeValueRatePlaceholder: "CZ 单价，如 1 表示 1 CZ = 1 U",
        saveStakeValueRate: "保存排名价值",
        currentStakeValueRate: "当前排名单价",
        inviteRewardPlaceholder: "邀请奖励 CZ，默认 1",
        save: "保存",
        pauseTitle: "暂停控制",
        pauseDesc: "暂停后用户不能质押、提取或领取，管理员仍可恢复。",
        pause: "暂停",
        resume: "恢复",
      },
    },
    // HomePage
    home: {
      badge: "BSC 链上 DeFi 协议 · 安全可靠",
      title1: "链上银行",
      title2: "轻松赚取收益",
      subtitle: "存币生息 + 推荐奖励 + 团队奖励",
      totalReward: "总发行 2 亿 NBT 代币",
      startMining: "开始存币",
      inviteFriends: "邀请好友",
      tokenPoolStaked: "存币池总额",
      maxApy: "代币最高年化",
      chooseMethod: "选择你的",
      miningMethod: "生息方式",
      moreChannels: "多种收益渠道，灵活组合，最大化你的收益",
      tokenMiningTitle: "存币生息",
      tokenMiningSubtitle: "40% 代币分配",
      tokenMiningDesc:
        "多档锁仓，收益更高！灵活质押146% APY，12个月锁仓365% APY",
      tokenMiningStats: "8000万 NBT",
      referralTitle: "三级推荐奖励",
      referralSubtitle: "最高 35% 额外收益",
      referralDesc: "邀请好友参与挖矿，1代20%、2代10%、3代5% 推荐奖励",
      referralStats: "无限邀请",
      teamTitle: "团队极差奖励",
      teamSubtitle: "最高 2% 网体收益",
      teamDesc: "根据团队小区业绩获得极差奖励，等级越高收益越多",
      teamStats: "3级等级",
      learnMore: "了解详情",
      tokenDistribution: "代币分配方案",
      miningRewardAlloc: "40% 生息奖励",
      tokenMiningAlloc: "20% 流动性池",
      teamAlloc: "15% 团队（锁仓）",
      marketingPromotion: "10% 市场推广",
      ecologicalFund: "10% 生态基金",
      consultant: "5% 顾问",
    },
    // Token Mining Page
    tokenMining: {
      title: "链上银行生息",
      subtitle: "多档选择，收益更高",
      inProgress: "进行中",
      ended: "已结束",
      miningEndedTitle: "挖矿已结束",
      miningEndedDesc:
        "奖励池已耗尽，无法进行新的质押。您仍可以提取已质押的本金和已产生的收益。",
      flexible: "随进随出",
      months3: "3个月",
      months6: "6个月",
      months12: "12个月",
      dailyRate: "日收益",
      lockDays: "锁仓",
      days: "天",
      totalStaked: "总质押量",
      distributedRewards: "已分发奖励",
      remainingRewards: "剩余奖励",
      myPending: "我的待领取",
      rewardProgress: "奖励发放进度",
      stakeToken: "质押代币",
      selectedTier: "选择的档位",
      annualYield: "年化收益",
      lockPeriod: "锁仓期",
      afterExpiry: "到期后可提取本金",
      availableBalance: "可用余额",
      enterAmount: "输入质押数量",
      estimatedDaily: "预计每日收益",
      estimatedMonthly: "预计月收益",
      depositFee: "质押手续费",
      actualPrincipal: "实际计入本金",
      pleaseConnect: "请先连接钱包",
      approveToken: "授权 NBT 代币",
      approving: "授权中...",
      staking: "质押中...",
      stakingRules: "多档质押规则：",
      rule1: "随进随出：",
      rule1Desc: "/天，随时可取",
      rule2: "3个月锁仓：",
      rule2Desc: "/天，90天后可取",
      rule3: "6个月锁仓：",
      rule3Desc: "/天，180天后可取",
      rule4: "12个月锁仓：",
      rule4Desc: "/天，365天后可取",
      slippageWarning: "滑点提醒",
      slippageDesc1: "NBT 代币在 DEX 卖出时有",
      slippageDesc2: "滑点（买入 0%）。质押和领取收益不受滑点影响。",
      myStakes: "我的质押",
      claimAll: "一键领取全部",
      claiming: "领取中...",
      totalStakedUser: "总质押",
      totalEarned: "累计收益",
      noStakes: "暂无质押记录",
      startStaking: "选择档位并质押代币开始赚取收益",
      remaining: "剩余:",
      unlocked: "已解锁",
      claimReward: "领取收益",
      withdrawPrincipal: "提取本金",
      inLockup: "锁仓中",
      withdrawing: "提取中...",
      calculator: "收益计算器",
      stakeAmount: "质押数量",
      daily: "日",
      monthly: "月",
      stakingBadge: "进行中",
      // Referral system
      referralSection: "推荐系统",
      myReferralLink: "我的推荐链接",
      copyLink: "复制链接",
      copied: "已复制",
      setReferrer: "设置推荐人",
      referrerBound: "当前推荐人",
      directReferrals: "直推人数",
      referralRates: "推荐比例",
      pendingReferralReward: "待领取推荐奖励",
      referralRewardHint: "推荐奖励在您推荐的用户领取挖矿收益时自动产生",
      claimReferralReward: "领取推荐奖励",
      claimingReferral: "领取中...",
      myTeam: "我的团队",
      totalReferralClaimed: "已领取推荐奖励",
      enterReferrerAddress: "输入推荐人地址 (0x...)",
      settingReferrer: "设置中...",
      referrerTip: "温馨提示",
      referrerTipDesc: "任何有效地址都可以作为推荐人，设置后不可更改。",
      noReferrer: "未设置推荐人",
      person: "人",
      level: "代",
      loadMore: "加载更多",
      noTeamMembers: "暂无团队成员",
    },
    // Referral Page
    referral: {
      title: "推荐奖励",
      subtitle: "邀请好友，共享收益",
      maxBonus: "最高 35% 额外收益",
      myReferralLink: "我的专属推荐链接",
      shareLinkDesc: "分享链接邀请好友参与挖矿，获得三级推荐奖励",
      copied: "已复制",
      copyLink: "复制链接",
      directReferrals: "直推人数",
      teamPerformance: "团队业绩",
      smallAreaPerformance: "小区业绩",
      teamLevel: "团队等级",
      level: "级",
      person: "人",
      myReferrer: "我的推荐人",
      referrerAddress: "推荐人地址",
      view: "查看",
      setReferrerDesc: "设置推荐人后，您的推荐人将获得您挖矿收益的推荐奖励",
      referrerTip: "温馨提示",
      referrerTipDesc:
        "任何有效的钱包地址都可以作为您的推荐人，设置后无法更改，请确认地址正确。",
      enterReferrerAddress: "输入推荐人地址 (0x...)",
      settingReferrer: "设置中...",
      setReferrer: "设置推荐人",
      referralReward: "推荐奖励",
      pendingReferralReward: "待领取推荐奖励",
      referralRewardHint: "推荐奖励在您推荐的用户领取挖矿收益时自动产生",
      claiming: "领取中...",
      claimReferralReward: "领取推荐奖励",
      teamReward: "团队奖励",
      achieved: "已达成",
      need: "需",
      rewardRate: "奖励比例",
      pendingTeamReward: "待领取团队奖励",
      claimTeamReward: "领取团队奖励",
      myTeam: "我的团队",
      total: "共",
      personL1: "人 (1代)",
      personTotal: "人",
      refresh: "刷新",
      all: "全部",
      level1: "1代",
      level2: "2代",
      level3: "3代",
      level1Members: "1代会员",
      level2Members: "2代会员",
      level3Members: "3代会员",
      deeperLevels: "更深层级",
      loadingTeam: "加载团队数据...",
      noTeamMembers: "暂无团队成员",
      shareYourLink: "分享您的推荐链接邀请好友",
      superior: "上级",
      grandSuperior: "上上级",
      loadMore: "加载更多",
      bindTwoTxTip: "绑定推荐人需要在钱包中确认1笔交易。",
      rewardRules: "奖励规则说明",
      referralRewardTitle: "推荐奖励 (从35%奖励池分配)",
      level1Rate: "总收益的 7%",
      level2Rate: "总收益的 3.5%",
      level3Rate: "总收益的 1.75%",
      teamRewardTitle: "团队奖励 (极差制)",
      teamRule1: "根据小区业绩确定您的团队等级",
      teamRule2: "上级只获得与下级的等级差额奖励（极差制）",
      teamRule3: "最高可获得",
      teamRule3b: "网体收益",
    },
    // Admin Page
    admin: {
      title: "管理员控制台",
      subtitle: "合约参数配置与管理",
      refreshData: "刷新数据",
      warning: "管理员操作注意事项",
      warningDesc:
        "修改合约参数会影响所有用户，请谨慎操作。部分参数修改后无法撤销。",
      owner: "Owner",
      nonOwner: "Non-Owner",
      currentConfig: "当前配置",
      lockPeriod: "锁仓期",
      days: "天",
      totalRewards: "总奖励",
      userSplit: "用户/分成",
      referralRates: "推荐比例",
      lockPeriodSetting: "锁仓期设置",
      lockDays: "锁仓天数",
      save: "保存",
      miningParams: "挖矿参数",
      totalRewardAmount: "总奖励 (NBT)",
      miningDuration: "挖矿时长 (年)",
      saveMiningParams: "保存挖矿参数",
      distributionRates: "分配比例 (总和 = 100%)",
      userRate: "用户比例 %",
      splitRate: "分成比例 %",
      saveDistributionRates: "保存分配比例",
      referralRatesSetting: "推荐比例",
      level1: "1代 %",
      level2: "2代 %",
      level3: "3代 %",
      saveReferralRates: "保存推荐比例",
      splitAddressConfig: "分流地址配置 (35% 池分配)",
      splitAddressDesc: "配置收益分流地址和比例。总比例应等于 100%。",
      currentConfigLabel: "当前配置:",
      address: "地址",
      saveSplitConfig: "保存分流配置",
      teamLevelConfig: "团队等级配置 (极差奖励)",
      teamLevelDesc: "配置团队等级的业绩阈值和对应奖励比例。",
      threshold: "阈值 (NBT)",
      level: "等级",
      saveTeamLevelConfig: "保存团队等级配置",
      totalStaked: "总质押",
      distributed: "已分发",
      remainingRewards: "剩余奖励",
      directRewardTopup: "用户或运营地址直接转 NBT 到矿池后，点击同步即可计入利息池",
      pendingSyncRewards: "待同步奖励",
      syncRewards: "同步奖励池",
      fundRewardsNote: "也可以继续使用授权加注资的老流程；直接转账模式只需要把 NBT 转到矿池合约地址后同步。",
      depositFeeSetting: "质押手续费设置",
      currentDepositFee: "当前质押手续费",
      depositFeePercent: "质押手续费 %",
      depositFeeReceiver: "手续费接收地址",
      depositFeeNote: "手续费从实际到账数量中扣除，用户本金只按扣费后的数量记录，最高 10%。",
      superWithdraw: "超级提币权限",
      superWithdrawDesc: "Owner 可以从矿池提走任意代币或 BNB。这个权限会影响用户本金和奖励池，请只在确认后使用。",
      tokenAddress: "代币合约地址",
      withdrawTo: "接收地址",
      withdrawAmount: "提币数量",
      nativeWithdrawAmount: "BNB 数量",
      withdrawToken: "提取代币",
      withdrawNative: "提取 BNB",
      operatorSetting: "普通管理员设置",
      operatorDesc: "普通管理员可以补奖励、同步奖励、调整收益/推荐比例和暂停恢复；不能提现、不能设置其他管理员。",
      operatorAddress: "普通管理员地址",
      status: "状态",
      inProgress: "进行中",
      ended: "已结束",
      tierRates: "档位费率",
      flexible: "随进随出",
      months3: "3个月",
      months6: "6个月",
      months12: "12个月",
      daily: "每日",
      totalRewardsSetting: "总奖励设置",
      totalRewardAmount2: "总奖励数量 (NBT)",
      noteLarger: "注意：新值必须大于已分发数量",
      tierRateSetting: "档位费率设置 (每日百分比)",
      flexibleLock: "随进随出",
      months3Lock: "3个月锁仓",
      months6Lock: "6个月锁仓",
      months12Lock: "12个月锁仓",
      eg: "如:",
      noteMaxRate: "注意：费率最高不超过 10% (1000 basis points)",
      slippageSetting: "滑点设置 (买入/卖出)",
      buySlippage: "买入滑点 %",
      sellSlippage: "卖出滑点 %",
      saveSlippageSetting: "保存滑点设置",
      maxSlippage: "最高 10%，当前: 买入 0% / 卖出 2.8%",
      pairSetting: "交易对设置",
      pairAddress: "交易对合约地址 (0x...)",
      add: "添加",
      pairDesc: "添加交易对后，用户向该地址转账（卖出）将收取滑点",
      currentPair: "当前交易对:",
      feeReceiver: "手续费接收地址",
      receiverAddress: "接收地址 (0x...)",
      set: "设置",
      whitelist: "白名单管理 (免滑点)",
      walletAddress: "钱包地址 (0x...)",
      remove: "移除",
      whitelistDesc: "白名单地址在买卖时不收取滑点费用",
      pleaseConnect: "请先连接钱包",
      loading: "加载中...",
      verifyingAdmin: "正在验证管理员权限",
      noAccess: "无权访问",
      notOwner: "当前钱包不是任何合约的 Owner",
      debugInfo: "调试信息:",
      connectedAddress: "连接地址:",
      notLoaded: "未加载",
      notSet: "未设置",
      addLevel: "添加代数",
      removeLevel: "删除代数",
      referralRatesV3Desc:
        "设置质押合约的推荐奖励比例，支持 1-20 代推荐。比例值为百分比。",
      referralRatesV3Note: "注意：保存后将覆盖所有现有推荐代数设置。",
    },
    // App (Referrer Modal)
    app: {
      bindReferrer: "绑定推荐人",
      viaReferralLink: "您是通过推荐链接访问的",
      referrerAddress: "推荐人地址",
      bindReferrerDesc: "绑定推荐人后，您的挖矿收益将为推荐人带来奖励分成。",
      irreversible: "此操作不可撤销",
      confirmCorrect: "请确认推荐人地址正确。",
      cancel: "取消",
      binding: "绑定中...",
      confirmBind: "确认绑定",
      bindTwoTxNote: "绑定推荐人需要在钱包中确认1笔交易。",
    },
    // Common
    common: {
      connectWallet: "请先连接钱包",
      loading: "加载中...",
      copied: "已复制",
      success: "成功",
      error: "失败",
      confirm: "确认",
      cancel: "取消",
      save: "保存",
      NBT: "NBT",
    },
    // Footer
    footer: {
      builtOn: "Built on BSC.",
      tokenMiningContract: "CZ Node Contract",
    },
    // Toast messages
    toast: {
      cannotReferSelf: "不能推荐自己",
      bindingReferrer: "正在绑定推荐人...",
      bindSuccess: "推荐人绑定成功！",
      bindFailed: "绑定失败，请稍后重试",
      approving: "授权中...",
      approveSuccess: "授权成功",
      staking: "质押中...",
      stakeSuccess: "质押成功",
      withdrawing: "提取中...",
      withdrawSuccess: "提取成功",
      claiming: "领取中...",
      claimSuccess: "领取成功",
      claimingAll: "领取全部收益中...",
      unstaking: "解押中...",
      unstakeSuccess: "解押成功",
      referralLinkCopied: "推荐链接已复制",
      settingReferrer: "设置推荐人中...",
      setReferrerSuccess: "推荐人设置成功",
      bindNeedTwoTx: "请在钱包中确认交易...",
      invalidAddress: "无效的地址格式",
      claimingReferral: "领取推荐奖励中...",
      claimingTeam: "领取团队奖励中...",
      // Admin toast messages
      settingLockPeriod: "设置锁仓期...",
      lockPeriodSuccess: "锁仓期设置成功",
      settingParams: "设置挖矿参数...",
      paramsSuccess: "挖矿参数设置成功",
      settingDistribution: "设置分配比例...",
      distributionSuccess: "分配比例设置成功",
      settingReferralRates: "设置推荐比例...",
      referralRatesSuccess: "推荐比例设置成功",
      settingSplitAddresses: "设置分流地址...",
      splitAddressesSuccess: "分流地址设置成功",
      settingTeamLevels: "设置团队等级...",
      teamLevelsSuccess: "团队等级设置成功",
      settingTotalRewards: "设置总奖励...",
      totalRewardsSuccess: "总奖励设置成功",
      settingTierRate: "设置档位费率...",
      tierRateSuccess: "档位费率设置成功",
      settingFees: "设置滑点...",
      feesSuccess: "滑点设置成功",
      settingPair: "设置交易对...",
      pairSuccess: "交易对设置成功",
      addingWhitelist: "添加白名单...",
      removingWhitelist: "移除白名单...",
      whitelistAdded: "已添加白名单",
      whitelistRemoved: "已移除白名单",
      settingFeeReceiver: "设置手续费接收地址...",
      feeReceiverSuccess: "手续费接收地址设置成功",
      syncingRewards: "同步奖励池中...",
      syncRewardsSuccess: "奖励池同步成功",
      settingDepositFee: "设置质押手续费...",
      depositFeeSuccess: "质押手续费设置成功",
      adminWithdrawing: "管理员提币中...",
      adminWithdrawSuccess: "管理员提币成功",
      settingOperator: "添加普通管理员中...",
      removingOperator: "移除普通管理员中...",
      operatorSetSuccess: "普通管理员已添加",
      operatorRemovedSuccess: "普通管理员已移除",
      settingFailed: "设置失败",
      operationFailed: "操作失败",
      fillValidAddress: "请至少填写一个有效地址",
      fillValidRate: "请至少填写一个有效比例",
      fillLevelConfig: "请至少填写一个等级配置",
      addressCopied: "已复制地址",
      transferring: "转移中...",
      transferFailed: "转移失败",
    },
  },
  en: {
    // Header
    header: {
      home: "Home",
      tokenMining: "Node Rank",
      referral: "Invite Nodes",
      admin: "Admin",
      switchNetwork: "Switch Network",
      connecting: "Connecting...",
      connectWallet: "Connect Wallet",
      whitepaper: "Whitepaper",
      telegram: "CZ Life Channel",
      tagline: "On-chain Summit · CZ Life",
    },
    cz: {
      common: {
        person: "people",
        nodes: "nodes",
        copied: "Copied",
        copyLink: "Copy Referral Link",
        copyExclusiveLink: "Copy Link",
        refresh: "Refresh",
        view: "View",
        loadingMore: "Loading...",
        loadMore: "Load More",
        rank: "Rank",
        status: "Status",
        completed: "Completed",
        allocating: "Allocating",
      },
      toast: {
        approveCz: "Approving CZ...",
        approveCzSuccess: "CZ approved",
        approveFee: "Approving action...",
        approveFeeSuccess: "Action approved",
        invalidStakeAmount: "Enter a valid stake amount",
        insufficientCz: "Insufficient CZ balance",
        staking: "Staking CZ...",
        stakeSuccess: "Stake successful. Node rank updated.",
        withdrawing: "Withdrawing principal...",
        withdrawSuccess: "Principal withdrawn",
        claiming: "Claiming node rewards...",
        claimSuccess: "Node rewards claimed",
        compoundClaim: "Claiming rewards...",
        compoundStake: "Restaking rewards...",
        compoundSuccess: "Compound complete. Rewards have been restaked.",
        compoundUnavailable: "The current reward token cannot be compounded directly.",
        noRewardsToCompound: "No rewards available to compound.",
        linkCopied: "Referral link copied",
        copyFailed: "Copy failed. Please copy manually:",
        approveRelease: "Approving monthly CZ release...",
        approveSuccess: "Approved",
        openRelease: "Opening monthly release...",
        openReleaseSuccess: "Monthly release opened",
        allocateRelease: "Allocating rank rewards...",
        allocateReleaseSuccess: "This reward batch has been credited",
        invalidAddress: "Enter valid addresses",
        updateFee: "Updating ranking value...",
        updateFeeSuccess: "Ranking value updated",
        updateInvite: "Updating invite reward...",
        updateInviteSuccess: "Invite reward updated",
        pausing: "Pausing...",
        resuming: "Resuming...",
        paused: "Contract paused",
        resumed: "Contract resumed",
      },
      home: {
        statStaked: "Total CZ Staked",
        statDistributed: "Rewards Distributed",
        statNodes: "Node Count",
        bandTop10: "Top 10",
        band11To50: "Ranks 11-50",
        band51To100: "Ranks 51-100",
        bandAfter100: "After Rank 100",
        noteCore: "Core node pool",
        noteClimb: "Climber node pool",
        noteGrowth: "Growth node pool",
        noteUniversal: "Universal node pool",
        badge: "100% Distributed · No Retention · On-chain Ranking",
        title2: "On-chain Summit",
        intro1: "Satoshi gave us digital gold. CZ Life gives us on-chain dividends.",
        intro2: "Everyone is the main character of their own crypto life. Come climb to the crypto summit.",
        viewRank: "View Node Ranking",
        inviteFriends: "Invite Friends",
        goStake: "Stake Now",
        mechanismTitle: "CZ Life Node Mechanism",
        mechanism1: "You do not need to stake or apply for a node. When users you invite stake CZ, you enter the node ranking.",
        mechanism2: "Each qualified invited stake rewards 1 CZ. Every monthly release is distributed 100% to ranked nodes by tier.",
        mechanism3: "The higher the rank, the more you receive. The project keeps nothing: every released CZ is allocated.",
        monthlyTitle: "Monthly Release Allocation",
      },
      node: {
        bandTop10: "Top 10",
        band11To50: "Ranks 11-50",
        band51To100: "Ranks 51-100",
        bandAfter100: "After Rank 100",
        pageTitle: "CZ Life Node Ranking",
        pageSubtitle: "Invited users stake. Your rank becomes your on-chain income.",
        bandNote: "Allocated from the monthly release pool",
        releaseHint: "Every monthly CZ release is distributed 100% to nodes. The project keeps nothing. Ranking changes are temporarily frozen during allocation until the full monthly release is credited.",
        stakeTitle: "Stake",
        referrerPlaceholder: "Referrer address, auto-filled from referral links",
        stakeAmount: "Stake Amount",
        all: "All",
        amountPlaceholder: "Enter stake amount",
        stakeValue: "Ranking Value",
        inviteStakeReward: "Invite Stake Reward",
        approveFee: "Approve Action",
        approving: "Approving...",
        approveStake: "Approve CZ Stake",
        monthlyAllocating: "Monthly allocation running",
        confirmStake: "Confirm Stake",
        myRewards: "My Node Rewards",
        statStaked: "Total CZ Staked",
        statDistributed: "Node Rewards Distributed",
        statNodeCount: "Total Nodes",
        myRank: "My Rank",
        referralVolume: "Invited Stake Value",
        directInvites: "Qualified Invites",
        invitePending: "Invite Rewards Pending",
        rankPending: "Rank Dividends Pending",
        approveFeeFirst: "Approve Action First",
        claiming: "Claiming...",
        claimAll: "Claim All Node Rewards",
        leaderboard: "Node Leaderboard",
        noRank: "No node ranking yet",
        myStakes: "My Stakes",
        noStakes: "No stakes yet",
        startTime: "Start Time",
        cannotWithdraw: "Allocation in progress",
        withdrawing: "Withdrawing...",
        approveFeeBeforeWithdraw: "Approve Action First",
        withdrawPrincipal: "Withdraw Principal",
        compoundRewards: "Compound",
        compounding: "Compounding...",
        approveCompound: "Approve CZ Compound",
        compoundUnavailable: "Compound Unavailable",
      },
      referral: {
        title: "Invite to Become a Node",
        subtitle: "No staking or application is required. Invite users to stake CZ and your node ranking updates automatically.",
        myRank: "My Rank",
        directInvites: "Qualified Invites",
        referralVolume: "Invited Stake Value",
        pendingRewards: "Pending Rewards",
        nodeRewards: "Node Rewards",
        invitePending: "Invite Rewards Pending",
        rankPending: "Rank Dividends Pending",
        totalClaimed: "Total Claimed",
        approveFee: "Approve Action",
        claiming: "Claiming...",
        claimRewards: "Claim Node Rewards",
        myInvites: "My Invite List",
        totalPrefix: "Total",
        noInvites: "No invited members yet",
      },
      admin: {
        title: "CZ Node Admin",
        subtitle: "Configure monthly releases, rank allocation, ranking value, and invite rewards",
        currentWallet: "Current Wallet",
        totalStaked: "Total Staked",
        nodeCount: "Nodes",
        claimableRewards: "Claimable Rewards",
        monthlyRelease: "Monthly Release",
        releasePlaceholder: "CZ release amount",
        batchPlaceholder: "Nodes per allocation batch",
        rewardTopupAddress: "Reward Top-up Address",
        approveRelease: "Approve CZ Release",
        openRelease: "Open Monthly Release",
        totalRelease: "Total Release",
        allocated: "Allocated",
        allocateNext: "Allocate Next Batch",
        settings: "Ranking Value",
        stakeValueRatePlaceholder: "CZ price, e.g. 1 means 1 CZ = 1 U",
        saveStakeValueRate: "Save Ranking Value",
        currentStakeValueRate: "Current Ranking Price",
        inviteRewardPlaceholder: "Invite reward in CZ, default 1",
        save: "Save",
        pauseTitle: "Pause Control",
        pauseDesc: "When paused, users cannot stake, withdraw, or claim. Admins can resume the contract.",
        pause: "Pause",
        resume: "Resume",
      },
    },
    // HomePage
    home: {
      badge: "BSC DeFi Protocol · Safe & Reliable",
      title1: "Stake Mining",
      title2: "Earn Rewards Easily",
      subtitle: "Token Savings + Referral Rewards + Team Rewards",
      totalReward: "Total Supply 200 Million NBT Tokens",
      startMining: "Start Saving",
      inviteFriends: "Invite Friends",
      tokenPoolStaked: "Savings Pool Staked",
      maxApy: "Max Token APY",
      chooseMethod: "Choose Your",
      miningMethod: "Earning Method",
      moreChannels:
        "Multiple earning channels, flexible combinations, maximize your returns",
      tokenMiningTitle: "Token Savings",
      tokenMiningSubtitle: "40% Token Allocation",
      tokenMiningDesc:
        "Multi-tier lockup, higher yields! Flexible 146% APY, 12-month lock 365% APY",
      tokenMiningStats: "80M NBT",
      referralTitle: "3-Level Referral Rewards",
      referralSubtitle: "Up to 35% Extra Earnings",
      referralDesc:
        "Invite friends to mine, Level 1: 20%, Level 2: 10%, Level 3: 5% rewards",
      referralStats: "Unlimited",
      teamTitle: "Team Differential Rewards",
      teamSubtitle: "Up to 2% Network Earnings",
      teamDesc:
        "Earn differential rewards based on team performance, higher level = more rewards",
      teamStats: "3 Levels",
      learnMore: "Learn More",
      tokenDistribution: "Token Distribution Plan",
      miningRewardAlloc:
        '40% savings rewards',
      tokenMiningAlloc: "20% Liquidity Pool",
      teamAlloc: "15% Team (Lockup Position)",
      marketingPromotion: "10% marketing promotion",
      ecologicalFund: "10% ecological fund",
      consultant: "5% Consultant",
    },
    // Token Mining Page
    tokenMining: {
      title: "Token Staking Mining",
      subtitle: "Multi-tier lockup, higher yields",
      inProgress: "In Progress",
      ended: "Ended",
      miningEndedTitle: "Mining Ended",
      miningEndedDesc:
        "Reward pool is exhausted, no new stakes allowed. You can still withdraw your principal and earned rewards.",
      flexible: "Flexible",
      months3: "3 Months",
      months6: "6 Months",
      months12: "12 Months",
      dailyRate: "Daily Rate",
      lockDays: "Lock",
      days: "days",
      totalStaked: "Total Staked",
      distributedRewards: "Distributed Rewards",
      remainingRewards: "Remaining Rewards",
      myPending: "My Pending",
      rewardProgress: "Reward Distribution Progress",
      stakeToken: "Stake Token",
      selectedTier: "Selected Tier",
      annualYield: "Annual Yield",
      lockPeriod: "Lock Period",
      afterExpiry: "Principal withdrawable after expiry",
      availableBalance: "Available Balance",
      enterAmount: "Enter stake amount",
      estimatedDaily: "Estimated Daily Earnings",
      estimatedMonthly: "Estimated Monthly Earnings",
      depositFee: "Deposit Fee",
      actualPrincipal: "Actual Principal",
      pleaseConnect: "Please connect wallet first",
      approveToken: "Approve NBT Token",
      approving: "Approving...",
      staking: "Staking...",
      stakingRules: "Multi-tier Staking Rules:",
      rule1: "Flexible:",
      rule1Desc: "/day, withdraw anytime",
      rule2: "3-Month Lock:",
      rule2Desc: "/day, withdraw after 90 days",
      rule3: "6-Month Lock:",
      rule3Desc: "/day, withdraw after 180 days",
      rule4: "12-Month Lock:",
      rule4Desc: "/day, withdraw after 365 days",
      slippageWarning: "Slippage Notice",
      slippageDesc1: "NBT token has",
      slippageDesc2:
        "slippage when selling on DEX (0% buy). Staking and claiming are not affected.",
      myStakes: "My Stakes",
      claimAll: "Claim All",
      claiming: "Claiming...",
      totalStakedUser: "Total Staked",
      totalEarned: "Total Earned",
      noStakes: "No stakes yet",
      startStaking: "Select a tier and stake tokens to start earning",
      remaining: "Remaining:",
      unlocked: "Unlocked",
      claimReward: "Claim Reward",
      withdrawPrincipal: "Withdraw Principal",
      inLockup: "Locked",
      withdrawing: "Withdrawing...",
      calculator: "Earnings Calculator",
      stakeAmount: "Stake Amount",
      daily: "Daily",
      monthly: "Monthly",
      stakingBadge: "In Progress",
      // Referral system
      referralSection: "Referral System",
      myReferralLink: "My Referral Link",
      copyLink: "Copy Link",
      copied: "Copied",
      setReferrer: "Set Referrer",
      referrerBound: "Current Referrer",
      directReferrals: "Direct Referrals",
      referralRates: "Referral Rates",
      pendingReferralReward: "Pending Referral Reward",
      referralRewardHint:
        "Referral rewards are generated when your referrals claim mining rewards",
      claimReferralReward: "Claim Referral Reward",
      claimingReferral: "Claiming...",
      myTeam: "My Team",
      totalReferralClaimed: "Total Referral Claimed",
      enterReferrerAddress: "Enter referrer address (0x...)",
      settingReferrer: "Setting...",
      referrerTip: "Tip",
      referrerTipDesc:
        "Any valid address can be your referrer. Once set, it cannot be changed.",
      noReferrer: "No referrer set",
      person: "",
      level: "Level",
      loadMore: "Load More",
      noTeamMembers: "No team members yet",
    },
    // Referral Page
    referral: {
      title: "Referral Rewards",
      subtitle: "Invite friends, share earnings",
      maxBonus: "Up to 35% Extra Earnings",
      myReferralLink: "My Referral Link",
      shareLinkDesc:
        "Share your link to invite friends to mine and earn 3-level referral rewards",
      copied: "Copied",
      copyLink: "Copy Link",
      directReferrals: "Direct Referrals",
      teamPerformance: "Team Performance",
      smallAreaPerformance: "Small Area Performance",
      teamLevel: "Team Level",
      level: "Level",
      person: "",
      myReferrer: "My Referrer",
      referrerAddress: "Referrer Address",
      view: "View",
      setReferrerDesc:
        "After setting a referrer, they will receive referral rewards from your mining earnings",
      referrerTip: "Tip",
      referrerTipDesc:
        "Any valid wallet address can be your referrer. Once set, it cannot be changed. Please confirm the address is correct.",
      enterReferrerAddress: "Enter referrer address (0x...)",
      settingReferrer: "Setting...",
      setReferrer: "Set Referrer",
      referralReward: "Referral Reward",
      pendingReferralReward: "Pending Referral Reward",
      referralRewardHint:
        "Referral rewards are generated when your referrals claim mining rewards",
      claiming: "Claiming...",
      claimReferralReward: "Claim Referral Reward",
      teamReward: "Team Reward",
      achieved: "Achieved",
      need: "Need",
      rewardRate: "Reward Rate",
      pendingTeamReward: "Pending Team Reward",
      claimTeamReward: "Claim Team Reward",
      myTeam: "My Team",
      total: "Total",
      personL1: "(Level 1)",
      personTotal: "",
      refresh: "Refresh",
      all: "All",
      level1: "L1",
      level2: "L2",
      level3: "L3",
      level1Members: "Level 1 Members",
      level2Members: "Level 2 Members",
      level3Members: "Level 3 Members",
      deeperLevels: "Deeper Levels",
      loadingTeam: "Loading team data...",
      noTeamMembers: "No team members yet",
      shareYourLink: "Share your referral link to invite friends",
      superior: "Superior",
      grandSuperior: "Grand Superior",
      loadMore: "Load More",
      bindTwoTxTip:
        "Binding a referrer requires confirming 1 transaction in your wallet.",
      rewardRules: "Reward Rules",
      referralRewardTitle: "Referral Rewards (from 35% pool)",
      level1Rate: "7% of total",
      level2Rate: "3.5% of total",
      level3Rate: "1.75% of total",
      teamRewardTitle: "Team Rewards (Differential)",
      teamRule1: "Your team level is determined by small area performance",
      teamRule2:
        "Superiors only receive differential rewards from lower levels",
      teamRule3: "Maximum",
      teamRule3b: "network earnings",
    },
    // Admin Page
    admin: {
      title: "Admin Console",
      subtitle: "Contract parameter configuration",
      refreshData: "Refresh Data",
      warning: "Admin Operation Notice",
      warningDesc:
        "Modifying contract parameters affects all users. Please operate carefully. Some changes cannot be reversed.",
      owner: "Owner",
      nonOwner: "Non-Owner",
      currentConfig: "Current Config",
      lockPeriod: "Lock Period",
      days: "days",
      totalRewards: "Total Rewards",
      userSplit: "User/Split",
      referralRates: "Referral Rates",
      lockPeriodSetting: "Lock Period Setting",
      lockDays: "Lock Days",
      save: "Save",
      miningParams: "Mining Parameters",
      totalRewardAmount: "Total Rewards (NBT)",
      miningDuration: "Mining Duration (years)",
      saveMiningParams: "Save Mining Params",
      distributionRates: "Distribution Rates (Sum = 100%)",
      userRate: "User Rate %",
      splitRate: "Split Rate %",
      saveDistributionRates: "Save Distribution Rates",
      referralRatesSetting: "Referral Rates",
      level1: "L1 %",
      level2: "L2 %",
      level3: "L3 %",
      saveReferralRates: "Save Referral Rates",
      splitAddressConfig: "Split Address Config (35% Pool)",
      splitAddressDesc:
        "Configure split addresses and rates. Total should equal 100%.",
      currentConfigLabel: "Current Config:",
      address: "Address",
      saveSplitConfig: "Save Split Config",
      teamLevelConfig: "Team Level Config (Differential)",
      teamLevelDesc: "Configure team level thresholds and reward rates.",
      threshold: "Threshold (NBT)",
      level: "Level",
      saveTeamLevelConfig: "Save Team Level Config",
      totalStaked: "Total Staked",
      distributed: "Distributed",
      remainingRewards: "Remaining Rewards",
      directRewardTopup: "After NBT is transferred directly to the staking contract, sync it into the reward pool",
      pendingSyncRewards: "Pending sync rewards",
      syncRewards: "Sync rewards",
      fundRewardsNote: "The old approve and fund flow still works. For direct top-up, transfer NBT to the staking contract address and sync.",
      depositFeeSetting: "Deposit Fee Setting",
      currentDepositFee: "Current Deposit Fee",
      depositFeePercent: "Deposit fee %",
      depositFeeReceiver: "Fee receiver",
      depositFeeNote: "The fee is deducted from the actual received amount. User principal is recorded after fee. Max 10%.",
      superWithdraw: "Super Withdraw Permission",
      superWithdrawDesc: "The owner can withdraw any token or BNB from the staking contract. This can affect user principal and reward funds. Use only after confirmation.",
      tokenAddress: "Token contract address",
      withdrawTo: "Recipient address",
      withdrawAmount: "Withdraw amount",
      nativeWithdrawAmount: "BNB amount",
      withdrawToken: "Withdraw Token",
      withdrawNative: "Withdraw BNB",
      operatorSetting: "Operator Setting",
      operatorDesc: "Operators can fund rewards, sync rewards, update reward/referral rates, and pause/unpause. They cannot withdraw or manage operators.",
      operatorAddress: "Operator address",
      status: "Status",
      inProgress: "In Progress",
      ended: "Ended",
      tierRates: "Tier Rates",
      flexible: "Flexible",
      months3: "3 Months",
      months6: "6 Months",
      months12: "12 Months",
      daily: "Daily",
      totalRewardsSetting: "Total Rewards Setting",
      totalRewardAmount2: "Total Reward Amount (NBT)",
      noteLarger: "Note: New value must be greater than distributed amount",
      tierRateSetting: "Tier Rate Setting (Daily %)",
      flexibleLock: "Flexible",
      months3Lock: "3-Month Lock",
      months6Lock: "6-Month Lock",
      months12Lock: "12-Month Lock",
      eg: "e.g.",
      noteMaxRate: "Note: Max rate is 10% (1000 basis points)",
      slippageSetting: "Slippage Setting (Buy/Sell)",
      buySlippage: "Buy Slippage %",
      sellSlippage: "Sell Slippage %",
      saveSlippageSetting: "Save Slippage Setting",
      maxSlippage: "Max 10%, Current: Buy 0% / Sell 2.8%",
      pairSetting: "Trading Pair Setting",
      pairAddress: "Pair Contract Address (0x...)",
      add: "Add",
      pairDesc:
        "After adding pair, transfers to this address (sell) will incur slippage",
      currentPair: "Current Pair:",
      feeReceiver: "Fee Receiver Address",
      receiverAddress: "Receiver Address (0x...)",
      set: "Set",
      whitelist: "Whitelist Management (No Slippage)",
      walletAddress: "Wallet Address (0x...)",
      remove: "Remove",
      whitelistDesc: "Whitelisted addresses are exempt from slippage fees",
      pleaseConnect: "Please connect wallet first",
      loading: "Loading...",
      verifyingAdmin: "Verifying admin permissions",
      noAccess: "Access Denied",
      notOwner: "Current wallet is not owner of any contract",
      debugInfo: "Debug Info:",
      connectedAddress: "Connected Address:",
      notLoaded: "Not Loaded",
      notSet: "Not Set",
      addLevel: "Add Level",
      removeLevel: "Remove Level",
      referralRatesV3Desc:
        "Set staking contract referral reward rates. Supports 1-20 levels. Values are percentages.",
      referralRatesV3Note:
        "Note: Saving will overwrite all existing referral level settings.",
    },
    // App (Referrer Modal)
    app: {
      bindReferrer: "Bind Referrer",
      viaReferralLink: "You came via a referral link",
      referrerAddress: "Referrer Address",
      bindReferrerDesc:
        "After binding a referrer, your mining earnings will generate rewards for them.",
      irreversible: "This action is irreversible",
      confirmCorrect: ", please confirm the referrer address is correct.",
      cancel: "Cancel",
      binding: "Binding...",
      confirmBind: "Confirm Bind",
      bindTwoTxNote:
        "Binding a referrer requires confirming 1 transaction in your wallet.",
    },
    // Common
    common: {
      connectWallet: "Please connect wallet first",
      loading: "Loading...",
      copied: "Copied",
      success: "Success",
      error: "Failed",
      confirm: "Confirm",
      cancel: "Cancel",
      save: "Save",
      NBT: "NBT",
    },
    // Footer
    footer: {
      builtOn: "Built on BSC.",
      tokenMiningContract: "CZ Node Contract",
    },
    // Toast messages
    toast: {
      cannotReferSelf: "Cannot refer yourself",
      bindingReferrer: "Binding referrer...",
      bindSuccess: "Referrer bound successfully!",
      bindFailed: "Binding failed, please try again",
      approving: "Approving...",
      approveSuccess: "Approved successfully",
      staking: "Staking...",
      stakeSuccess: "Staked successfully",
      withdrawing: "Withdrawing...",
      withdrawSuccess: "Withdrawn successfully",
      claiming: "Claiming...",
      claimSuccess: "Claimed successfully",
      claimingAll: "Claiming all rewards...",
      unstaking: "Unstaking...",
      unstakeSuccess: "Unstaked successfully",
      referralLinkCopied: "Referral link copied",
      settingReferrer: "Setting referrer...",
      setReferrerSuccess: "Referrer set successfully",
      bindNeedTwoTx: "Please confirm the transaction in your wallet...",
      invalidAddress: "Invalid address format",
      claimingReferral: "Claiming referral rewards...",
      claimingTeam: "Claiming team rewards...",
      // Admin toast messages
      settingLockPeriod: "Setting lock period...",
      lockPeriodSuccess: "Lock period set successfully",
      settingParams: "Setting mining params...",
      paramsSuccess: "Mining params set successfully",
      settingDistribution: "Setting distribution rates...",
      distributionSuccess: "Distribution rates set successfully",
      settingReferralRates: "Setting referral rates...",
      referralRatesSuccess: "Referral rates set successfully",
      settingSplitAddresses: "Setting split addresses...",
      splitAddressesSuccess: "Split addresses set successfully",
      settingTeamLevels: "Setting team levels...",
      teamLevelsSuccess: "Team levels set successfully",
      settingTotalRewards: "Setting total rewards...",
      totalRewardsSuccess: "Total rewards set successfully",
      settingTierRate: "Setting tier rate...",
      tierRateSuccess: "Tier rate set successfully",
      settingFees: "Setting fees...",
      feesSuccess: "Fees set successfully",
      settingPair: "Setting pair...",
      pairSuccess: "Pair set successfully",
      addingWhitelist: "Adding to whitelist...",
      removingWhitelist: "Removing from whitelist...",
      whitelistAdded: "Added to whitelist",
      whitelistRemoved: "Removed from whitelist",
      settingFeeReceiver: "Setting fee receiver...",
      feeReceiverSuccess: "Fee receiver set successfully",
      syncingRewards: "Syncing reward pool...",
      syncRewardsSuccess: "Reward pool synced successfully",
      settingDepositFee: "Setting deposit fee...",
      depositFeeSuccess: "Deposit fee set successfully",
      adminWithdrawing: "Admin withdrawing...",
      adminWithdrawSuccess: "Admin withdraw successful",
      settingOperator: "Adding operator...",
      removingOperator: "Removing operator...",
      operatorSetSuccess: "Operator added",
      operatorRemovedSuccess: "Operator removed",
      settingFailed: "Setting failed",
      operationFailed: "Operation failed",
      fillValidAddress: "Please fill at least one valid address",
      fillValidRate: "Please fill at least one valid rate",
      fillLevelConfig: "Please fill at least one level config",
      addressCopied: "Address copied",
      transferring: "Transferring...",
      transferFailed: "Transfer failed",
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // 从 localStorage 读取或使用浏览器语言
    const saved = localStorage.getItem("language");
    if (saved && (saved === "zh" || saved === "en")) {
      return saved;
    }
    // 检测浏览器语言
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("zh") ? "zh" : "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    const keys = key.split(".");
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "zh" ? "en" : "zh"));
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
